In [1]:
import numpy as np

In [3]:
np.random.random()
np.random.seed(1) # same value 

0.34739978611783673

In [4]:
np.random.uniform(3,10)

6.466037024891355

In [5]:
# generate arr of random

np.random.uniform(1,100,10).reshape(2,5)

array([[48.6661806 , 37.54590725, 62.55032081, 22.8365588 , 16.31451364],
       [53.58897545, 15.66176599, 50.52297764, 22.57003141, 33.04285403]])

In [8]:
a=np.random.randint(1,10,9)

In [ ]:
np.argmax(a) # gives index of max

In [11]:
# have to change all odd to -1
a=np.random.randint(1,10,6)

a[a%2==1]=-1
a

array([ 6,  6,  6, -1,  4, -1], dtype=int32)

In [19]:
# above is inplace  so.. 
# where(condition,T,F)
a=np.random.randint(1,30,6)
b=np.where(a%2==1,-1,a)
print(a)
print(b)

[21 20  5 10 22 16]
[-1 20 -1 10 22 16]
