In [1]:
import numpy as np

In [4]:
arr1=np.arange(24).reshape(6,4)
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
arr1[1::2]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [9]:
#fancy indexing

arr1[[0,1,5]] #row 0,1,5
arr1[0:,[0,3,2]]

array([[ 0,  3,  2],
       [ 4,  7,  6],
       [ 8, 11, 10],
       [12, 15, 14],
       [16, 19, 18],
       [20, 23, 22]])